url: https://benjamingent.github.io/
baseurl: /

# Site settings
title: LAZY ASS ENGINEERING
email: your-email@domain.com
description: "THIS ONE FOR MA HOMIES"

# Team names, titles and social links
people:
- name: BEN MUFUCKA
  pic: 1
  position: DP STUDENT AT MOSCOW ECONOMIC SCHOOL
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Moscow
  - line: Russia

# Build settings
markdown: kramdown
permalink: pretty