url: https://benjamingent.github.io/
baseurl: /

# Site settings
title: Superconductors at school
email: your-email@domain.com
description: "Small blog about my explorations"

# Team names, titles and social links
people:
- name: Benjamin Gentsis
  pic: 1
  position: DP STUDENT AT MOSCOW ECONOMIC SCHOOL
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/BejaminGent

# Postal address (add as many lines as necessary)
address:
  - line: Moscow
  - line: Russia

# Build settings
markdown: kramdown
permalink: pretty